In [3]:
import numpy as np

In [4]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
print(np.amax(X, axis=0))
y = np.array(([92], [86], [89]), dtype=float)


X = X/np.amax(X, axis=0)
y = y/100 

[3. 9.]


In [5]:
class Neural_Network(object):
    def __init__(self):
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3) # final activation function
        return o 

    def sigmoid(self, s):
        # activation function 
        return 1/(1+np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propgate through the network
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

        self.W1 += l_rate*X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += l_rate*self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

    def train (self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

In [6]:
NN = Neural_Network()
l_rate=0.1
for i in range(30): # trains the NN 1,000 times
    print("Epoch:",i)
    print("l_rate",l_rate)
    print ("Input: \n",str(X))
    print ("Actual Output: \n",str(y) )
    print ("Predicted Output: \n",str(NN.forward(X)) )
    print ("Loss: \n",str(np.mean(np.square(y - NN.forward(X)))))
    print ("\n")
    NN.train(X, y)

Epoch: 0
l_rate 0.1
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.58229267]
 [0.54229474]
 [0.58944813]]
Loss: 
 0.10177143288864755


Epoch: 1
l_rate 0.1
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.58651014]
 [0.54636792]
 [0.59386856]]
Loss: 
 0.09909146769716427


Epoch: 2
l_rate 0.1
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.59066197]
 [0.55037869]
 [0.59821715]]
Loss: 
 0.09648870742358112


Epoch: 3
l_rate 0.1
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.59474871]
 [0.55432749]
 [0.60249453]]
Loss: 
 0.09396115860953323


Epoch: 4
l_rate 0.1
Input: 
 [[0.6666666